services:
  # Development service
  dev:
    build:
      context: .
      target: development
    ports:
      - "3000:3000"
    volumes:
      - .:/app
      - /app/node_modules  # Prevent overwriting node_modules
    environment:
      - NODE_ENV=development

  # Production service (for testing production build locally)
  prod:
    build:
      context: .
      target: production
    ports:
      - "8080:80" 
